import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/home/Navbar";
import Footer from "./components/layouts/Footer";

export const inter = Inter ({
  weight: [ "100", "200", "400", "500", "600", "800" ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased w-11/12 mx-auto `}
      >
        <Navbar />
        <mani className="min-h-[calc(100vh - 320px)]">
          
          {children}
        </mani>
        <Footer />
      </body>
    </html>
  );
}
